language: go

env: GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

install: true

before_script:
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.27.0

script:
  - ./bin/golangci-lint run
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)